### PR TITLE
Add note about helper for projects using Mocha

### PR DESCRIPTION
**Pull request by cball**
With Mocha, you don't use the moduleForAcceptance helper (in fact in most of our projects we remove it). I thought this might clarify where to add the import in those cases.

As a followup question, is there any downside that you can think of to making this the recommended way to add the helper?

### CODE REVIEW

**Comment by fotinakis** [comment]
Oo I think you're right... I think we should just startApp for everything, which also makes the app/addon distinction moot.

Can you try this in your startApp?
```js
import _ from './percy/register-helpers';
```
I think we'll make the "_" part of the official recommendation, because people get confused that it's not a named import. I've also removed the redundant "../helpers" path.

**Comment by fotinakis** [comment]
My preference would of course be to find an ember-cli way to have an addon automatically register async test helpers so this import isn't even needed at all, but I don't think there's a happy path for that.

**Comment by fotinakis** [comment]
Ugh it looks like _ still throws lint errors:
```
helpers/start-app.js: line 4, col 8, '_' is defined but never used.
```
Sooo... back to `import './percy/register-helpers';`

**Comment by fotinakis** [comment]
Yup ok, GREAT idea! Implemented it in the ember-percy addon and in the percy-web app and it works great. Just need to make sure it works with a QUnit app before changing the docs. This will let us simplify everything into something like this:


```md
1. Register the percy test helpers for acceptance tests.
   * Add `import './percy/register-helpers';` to `tests/helpers/start-app.js`.
```

**Comment by fotinakis** [comment]
Closed by https://github.com/percy/percy-docs/commit/2c7851e49235eaf36dff0d3961b44aee09c7c645, thanks!

**Comment by cball** [comment]
@fotinakis perfect, that's exactly what I was thinking! Sorry I missed the notifications :)

**Pull request closed without merging**
